# Generated by Django 4.2.7 on 2025-09-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('validation', 'Validation Summary'), ('patient', 'Patient Records'), ('code_usage', 'Code Usage Analysis'), ('compliance', 'EHR Compliance'), ('audit', 'Audit Report')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('code_system', models.CharField(default='all', max_length=20)),
                ('data', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
