# Generated by Django 4.2.7 on 2025-09-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_diagnosis_id_alter_treatment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('code_system', models.CharField(choices=[('ICD-11', 'ICD-11'), ('NAMASTE', 'NAMASTE'), ('CPT', 'CPT'), ('HCPCS', 'HCPCS')], max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_code', models.CharField(max_length=20)),
                ('submitted_code_system', models.CharField(max_length=20)),
                ('validation_result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('validated_by', models.CharField(max_length=255)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis')),
                ('matched_master_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medicalcode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.treatment')),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('code_rejected', 'Code Rejected'), ('validation_failed', 'Validation Failed'), ('code_suggestion', 'Code Suggestion')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis')),
                ('related_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('related_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalcode',
            index=models.Index(fields=['code', 'code_system'], name='api_medical_code_8a5954_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcode',
            index=models.Index(fields=['code_system', 'is_active'], name='api_medical_code_sy_4cd525_idx'),
        ),
        migrations.AddIndex(
            model_name='validationhistory',
            index=models.Index(fields=['validation_result', 'validated_at'], name='api_validat_validat_642409_idx'),
        ),
        migrations.AddIndex(
            model_name='validationhistory',
            index=models.Index(fields=['patient', 'validated_at'], name='api_validat_patient_1d6879_idx'),
        ),
    ]
